ekyna_sitemap_index:
    path: /sitemap.xml
    defaults:
        _controller: "EkynaSitemapBundle:Sitemap:index"
    methods: [GET]

ekyna_sitemap_sitemap:
    path: /sitemaps/{sitemap}.xml
    defaults:
        _controller: "EkynaSitemapBundle:Sitemap:sitemap"
    methods: [GET]
    requirements:
        group: "[a-z-]+"
